// src/App.tsx
import { useState, useCallback, useEffect } from 'react'
import './App.css'
import { Gallery } from './components/Gallery'
import { ExportPanel } from './components/ExportPanel'
import { UnifiedEditor } from './components/UnifiedEditor'
import { CubePreview } from './components/CubePreview'
import { PromptGenerator } from './components/PromptGenerator'
import type { SpectralCube } from './types/cube'
import { createDefaultCube } from './types/cube'

/** Mobile navigation tabs */
type MobileTab = 'gallery' | 'preview' | 'editor' | 'tools'

/** Breakpoint for mobile detection */
const MOBILE_BREAKPOINT = 768
const TABLET_BREAKPOINT = 1024

/** Hook to detect device type based on viewport width */
function useDeviceType() {
  const [deviceType, setDeviceType] = useState<'mobile' | 'tablet' | 'desktop'>(() => {
    if (typeof window === 'undefined') return 'desktop'
    const width = window.innerWidth
    if (width < MOBILE_BREAKPOINT) return 'mobile'
    if (width < TABLET_BREAKPOINT) return 'tablet'
    return 'desktop'
  })

  useEffect(() => {
    const handleResize = () => {
      const width = window.innerWidth
      if (width < MOBILE_BREAKPOINT) {
        setDeviceType('mobile')
      } else if (width < TABLET_BREAKPOINT) {
        setDeviceType('tablet')
      } else {
        setDeviceType('desktop')
      }
    }

    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [])

  return deviceType
}

function App() {
  // Current cube state
  const [currentCube, setCurrentCube] = useState<SpectralCube | null>(() =>
    createDefaultCube('default_cube')
  )

  // Mobile navigation state
  const [activeTab, setActiveTab] = useState<MobileTab>('gallery')
  const deviceType = useDeviceType()
  const isMobile = deviceType === 'mobile'

  // Handle cube selection from gallery
  const handleCubeSelect = useCallback((cube: SpectralCube) => {
    setCurrentCube(cube)
  }, [])

  // Handle cube load from export panel
  const handleCubeLoad = useCallback((cube: SpectralCube) => {
    setCurrentCube(cube)
  }, [])

  // Handle cube change from undo/redo
  const handleCubeChange = useCallback((cube: SpectralCube) => {
    setCurrentCube(cube)
  }, [])

  // Handle cube update from UnifiedEditor
  const handleCubeUpdate = useCallback((cube: SpectralCube) => {
    setCurrentCube(cube)
  }, [])

  // Handle cube generation from PromptGenerator
  const handleCubeGenerated = useCallback((cube: SpectralCube) => {
    setCurrentCube(cube)
  }, [])

  // Mobile swipe handling for tab navigation
  const handleSwipe = useCallback(
    (direction: 'left' | 'right') => {
      const tabs: MobileTab[] = ['gallery', 'preview', 'editor', 'tools']
      const currentIndex = tabs.indexOf(activeTab)

      if (direction === 'left' && currentIndex < tabs.length - 1) {
        setActiveTab(tabs[currentIndex + 1])
      } else if (direction === 'right' && currentIndex > 0) {
        setActiveTab(tabs[currentIndex - 1])
      }
    },
    [activeTab]
  )

  // Touch swipe detection
  useEffect(() => {
    if (!isMobile) return

    let touchStartX = 0
    let touchEndX = 0
    const minSwipeDistance = 50

    const handleTouchStart = (e: TouchEvent) => {
      touchStartX = e.changedTouches[0].screenX
    }

    const handleTouchEnd = (e: TouchEvent) => {
      touchEndX = e.changedTouches[0].screenX
      const distance = touchEndX - touchStartX

      if (Math.abs(distance) > minSwipeDistance) {
        handleSwipe(distance > 0 ? 'right' : 'left')
      }
    }

    const mainContent = document.querySelector('.app__mobile-content')
    if (mainContent) {
      mainContent.addEventListener('touchstart', handleTouchStart as EventListener)
      mainContent.addEventListener('touchend', handleTouchEnd as EventListener)

      return () => {
        mainContent.removeEventListener('touchstart', handleTouchStart as EventListener)
        mainContent.removeEventListener('touchend', handleTouchEnd as EventListener)
      }
    }
  }, [isMobile, handleSwipe])

  // Render mobile layout with tabs
  if (isMobile) {
    return (
      <div className="app app--mobile">
        <header className="app__header app__header--mobile">
          <h1>isocubic</h1>
        </header>

        {/* Mobile tab navigation */}
        <nav className="app__mobile-nav">
          <button
            type="button"
            className={`app__mobile-tab ${activeTab === 'gallery' ? 'app__mobile-tab--active' : ''}`}
            onClick={() => setActiveTab('gallery')}
            aria-selected={activeTab === 'gallery'}
          >
            <span className="app__mobile-tab-icon">🎨</span>
            <span className="app__mobile-tab-label">Gallery</span>
          </button>
          <button
            type="button"
            className={`app__mobile-tab ${activeTab === 'preview' ? 'app__mobile-tab--active' : ''}`}
            onClick={() => setActiveTab('preview')}
            aria-selected={activeTab === 'preview'}
          >
            <span className="app__mobile-tab-icon">👁️</span>
            <span className="app__mobile-tab-label">Preview</span>
          </button>
          <button
            type="button"
            className={`app__mobile-tab ${activeTab === 'editor' ? 'app__mobile-tab--active' : ''}`}
            onClick={() => setActiveTab('editor')}
            aria-selected={activeTab === 'editor'}
          >
            <span className="app__mobile-tab-icon">🎛️</span>
            <span className="app__mobile-tab-label">Editor</span>
          </button>
          <button
            type="button"
            className={`app__mobile-tab ${activeTab === 'tools' ? 'app__mobile-tab--active' : ''}`}
            onClick={() => setActiveTab('tools')}
            aria-selected={activeTab === 'tools'}
          >
            <span className="app__mobile-tab-icon">⚙️</span>
            <span className="app__mobile-tab-label">Tools</span>
          </button>
        </nav>

        {/* Mobile content panels */}
        <main className="app__mobile-content">
          {activeTab === 'gallery' && (
            <section className="app__mobile-panel">
              <Gallery onCubeSelect={handleCubeSelect} currentCube={currentCube} />
            </section>
          )}

          {activeTab === 'preview' && (
            <section className="app__mobile-panel app__mobile-panel--preview">
              <div className="app__current-cube app__current-cube--mobile">
                <h3 className="app__section-title">Current Cube</h3>
                {currentCube && (
                  <div className="app__cube-info">
                    <p>
                      <strong>Name:</strong> {currentCube.meta?.name || currentCube.id}
                    </p>
                    <p>
                      <strong>Material:</strong> {currentCube.physics?.material || 'Unknown'}
                    </p>
                    <p>
                      <strong>Tags:</strong> {currentCube.meta?.tags?.join(', ') || 'None'}
                    </p>
                  </div>
                )}
              </div>
              {/* 3D preview with interactive controls */}
              <div className="app__3d-preview app__3d-preview--mobile">
                <CubePreview
                  config={currentCube}
                  showGrid={true}
                  animate={false}
                  showShadows={true}
                />
                <p className="app__preview-hint">Use touch gestures to rotate and zoom</p>
              </div>
            </section>
          )}

          {activeTab === 'editor' && (
            <section className="app__mobile-panel">
              <UnifiedEditor
                currentCube={currentCube}
                onCubeUpdate={handleCubeUpdate}
                isMobile={true}
              />
            </section>
          )}

          {activeTab === 'tools' && (
            <section className="app__mobile-panel">
              <PromptGenerator
                onCubeGenerated={handleCubeGenerated}
                contextCubes={currentCube ? [currentCube] : undefined}
                enableAdvanced={true}
              />
              <ExportPanel
                currentCube={currentCube}
                onCubeLoad={handleCubeLoad}
                onCubeChange={handleCubeChange}
              />
            </section>
          )}
        </main>

        {/* Swipe indicator */}
        <div className="app__swipe-indicator">
          <span>Swipe to navigate</span>
        </div>
      </div>
    )
  }

  // Render tablet layout (vertical stack)
  if (deviceType === 'tablet') {
    return (
      <div className="app app--tablet">
        <header className="app__header">
          <h1>isocubic</h1>
          <p>Web editor for parametric cubes</p>
        </header>

        <main className="app__main app__main--tablet">
          {/* Preview area at top */}
          <section className="app__preview-section">
            <div className="app__3d-preview app__3d-preview--tablet">
              <CubePreview
                config={currentCube}
                showGrid={true}
                animate={false}
                showShadows={true}
              />
            </div>
            <div className="app__current-cube">
              <h3 className="app__section-title">Current Cube</h3>
              {currentCube && (
                <div className="app__cube-info">
                  <p>
                    <strong>Name:</strong> {currentCube.meta?.name || currentCube.id}
                  </p>
                  <p>
                    <strong>Material:</strong> {currentCube.physics?.material || 'Unknown'}
                  </p>
                  <p>
                    <strong>Tags:</strong> {currentCube.meta?.tags?.join(', ') || 'None'}
                  </p>
                </div>
              )}
            </div>
          </section>

          {/* Gallery and tools side by side */}
          <div className="app__tablet-panels">
            <section className="app__section">
              <Gallery onCubeSelect={handleCubeSelect} currentCube={currentCube} />
            </section>

            <section className="app__section app__section--sidebar">
              <PromptGenerator
                onCubeGenerated={handleCubeGenerated}
                contextCubes={currentCube ? [currentCube] : undefined}
                enableAdvanced={true}
              />
              <UnifiedEditor currentCube={currentCube} onCubeUpdate={handleCubeUpdate} />
              <ExportPanel
                currentCube={currentCube}
                onCubeLoad={handleCubeLoad}
                onCubeChange={handleCubeChange}
              />
            </section>
          </div>
        </main>
      </div>
    )
  }

  // Render desktop layout (original - 3D preview left, editor right)
  return (
    <div className="app app--desktop">
      <header className="app__header">
        <h1>isocubic</h1>
        <p>Web editor for parametric cubes</p>
      </header>

      <main className="app__main">
        {/* Left side: 3D preview and Gallery */}
        <section className="app__section app__section--main">
          <div className="app__3d-preview app__3d-preview--desktop">
            <CubePreview config={currentCube} showGrid={true} animate={false} showShadows={true} />
          </div>
          <Gallery onCubeSelect={handleCubeSelect} currentCube={currentCube} />
        </section>

        {/* Right side: Parameter editor and tools */}
        <section className="app__section app__section--sidebar">
          <PromptGenerator
            onCubeGenerated={handleCubeGenerated}
            contextCubes={currentCube ? [currentCube] : undefined}
            enableAdvanced={true}
          />
          <UnifiedEditor currentCube={currentCube} onCubeUpdate={handleCubeUpdate} />
          <ExportPanel
            currentCube={currentCube}
            onCubeLoad={handleCubeLoad}
            onCubeChange={handleCubeChange}
          />
        </section>
      </main>
    </div>
  )
}

export default App

// src/App.vue
<!--
  App.vue — Root component for isocubic
  Adaptive layout with desktop, tablet, and mobile support

  Phase 10, TASK 67: App.vue layout and adaptive design
-->
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useDeviceType } from './composables/useDeviceType'
import { useCubeEditor } from './composables/useCubeEditor'
import { useDevModeKeyboard } from './lib/devmode'
import { useAuthStore } from './lib/auth'
import Gallery from './components/Gallery.vue'
import ExportPanel from './components/ExportPanel.vue'
import CubePreview from './components/CubePreview.vue'
import UnifiedEditor from './components/UnifiedEditor.vue'
import ActionHistory from './components/ActionHistory.vue'
import PromptGenerator from './components/PromptGenerator.vue'
import GodModeWindow from './components/GodModeWindow.vue'
import ComponentInfo from './components/ComponentInfo.vue'
import DevModeIndicator from './components/DevModeIndicator.vue'
import './App.css'

// Device type detection
const { isTablet, isDesktop } = useDeviceType()

// Cube editor state
const { currentCube, updateCube, selectCube, loadCube } = useCubeEditor()

// DevMode keyboard shortcut (Ctrl+Shift+D)
useDevModeKeyboard()

// Auth store initialization
const authStore = useAuthStore()
onMounted(() => {
  authStore.initialize()
})

// Mobile tab navigation
type MobileTab = 'gallery' | 'preview' | 'editor' | 'tools'

const activeMobileTab = ref<MobileTab>('gallery')

const mobileTabs: { id: MobileTab; icon: string; label: string }[] = [
  { id: 'gallery', icon: '🎨', label: 'Gallery' },
  { id: 'preview', icon: '👁', label: 'Preview' },
  { id: 'editor', icon: '✏️', label: 'Editor' },
  { id: 'tools', icon: '🔧', label: 'Tools' },
]

// Touch swipe navigation for mobile
const touchStartX = ref(0)
const touchEndX = ref(0)
const SWIPE_THRESHOLD = 50

function handleTouchStart(e: TouchEvent) {
  touchStartX.value = e.changedTouches[0].screenX
}

function handleTouchEnd(e: TouchEvent) {
  touchEndX.value = e.changedTouches[0].screenX
  handleSwipe()
}

function handleSwipe() {
  const diff = touchStartX.value - touchEndX.value
  if (Math.abs(diff) < SWIPE_THRESHOLD) return

  const tabIds = mobileTabs.map((t) => t.id)
  const currentIndex = tabIds.indexOf(activeMobileTab.value)

  if (diff > 0 && currentIndex < tabIds.length - 1) {
    // Swipe left → next tab
    activeMobileTab.value = tabIds[currentIndex + 1]
  } else if (diff < 0 && currentIndex > 0) {
    // Swipe right → previous tab
    activeMobileTab.value = tabIds[currentIndex - 1]
  }
}

// Component metadata for DevMode
const APP_META = {
  id: 'app',
  name: 'App',
  version: '2.0.0',
  summary: 'Root application component with adaptive layout.',
  description:
    'App is the root component of isocubic. It provides adaptive layout for desktop, tablet, and ' +
    'mobile devices, integrates all subsystems (Gallery, Editor, Preview, Export, GOD MODE), and ' +
    'manages the global cube editing state through the useCubeEditor composable.',
  phase: 10,
  taskId: 'TASK 67',
  filePath: 'src/App.vue',
  history: [
    {
      version: '1.0.0',
      date: '2026-01-29T18:00:00Z',
      description: 'Initial Vue.js 3.0 stub during TASK 60',
      taskId: 'TASK 60',
      type: 'created' as const,
    },
    {
      version: '2.0.0',
      date: '2026-01-31T18:00:00Z',
      description: 'Full adaptive layout with all component integrations',
      taskId: 'TASK 67',
      type: 'updated' as const,
    },
  ],
  features: [
    {
      id: 'adaptive-layout',
      name: 'Adaptive Layout',
      description: 'Desktop, tablet, and mobile layouts with automatic switching',
      enabled: true,
      taskId: 'TASK 67',
    },
    {
      id: 'mobile-swipe',
      name: 'Touch Swipe Navigation',
      description: 'Swipe between tabs on mobile devices',
      enabled: true,
      taskId: 'TASK 67',
    },
    {
      id: 'cube-state-management',
      name: 'Cube State Management',
      description: 'Centralized cube state with undo/redo and autosave',
      enabled: true,
      taskId: 'TASK 67',
    },
  ],
  dependencies: [
    {
      name: 'Gallery',
      type: 'component',
      path: 'components/Gallery.vue',
      purpose: 'Cube gallery with presets and user cubes',
    },
    {
      name: 'ExportPanel',
      type: 'component',
      path: 'components/ExportPanel.vue',
      purpose: 'Export/import and undo/redo controls',
    },
    {
      name: 'CubePreview',
      type: 'component',
      path: 'components/CubePreview.vue',
      purpose: '3D cube preview with TresJS',
    },
    {
      name: 'UnifiedEditor',
      type: 'component',
      path: 'components/UnifiedEditor.vue',
      purpose: 'Main tabbed parameter editor',
    },
    {
      name: 'PromptGenerator',
      type: 'component',
      path: 'components/PromptGenerator.vue',
      purpose: 'AI-based cube generation',
    },
    {
      name: 'GodModeWindow',
      type: 'component',
      path: 'components/GodModeWindow.vue',
      purpose: 'GOD MODE developer tools',
    },
    {
      name: 'useDeviceType',
      type: 'hook',
      path: 'composables/useDeviceType.ts',
      purpose: 'Reactive device type detection',
    },
    {
      name: 'useCubeEditor',
      type: 'hook',
      path: 'composables/useCubeEditor.ts',
      purpose: 'Centralized cube editing state',
    },
  ],
  relatedFiles: [
    { path: 'src/App.css', type: 'style', description: 'Styles for all layout variants' },
    {
      path: 'src/composables/useDeviceType.ts',
      type: 'util',
      description: 'Device type composable',
    },
    {
      path: 'src/composables/useCubeEditor.ts',
      type: 'util',
      description: 'Cube editor composable',
    },
  ],
  props: [],
  tags: ['app', 'layout', 'responsive', 'root'],
  status: 'stable' as const,
  lastUpdated: '2026-01-31T18:00:00Z',
}
</script>

<template>
  <!-- Desktop Layout -->
  <div v-if="isDesktop" class="app app--desktop">
    <ComponentInfo :meta="APP_META">
      <header class="app__header">
        <h1>isocubic</h1>
        <p>Web editor for parametric cubes</p>
      </header>

      <main class="app__main">
        <!-- Gallery sidebar -->
        <section class="app__section app__section--sidebar">
          <Gallery :current-cube="currentCube" @cube-select="selectCube" />
        </section>

        <!-- Main content: preview + editor -->
        <section class="app__section app__section--main">
          <div class="app__current-cube">
            <h3 class="app__section-title">Preview</h3>
            <div class="app__3d-preview app__3d-preview--desktop">
              <CubePreview :config="currentCube" data-testid="cube-preview" />
            </div>
          </div>

          <PromptGenerator
            @cube-generated="selectCube"
            @cubes-generated="(cubes) => cubes.length > 0 && selectCube(cubes[0])"
          />

          <UnifiedEditor :cube="currentCube" @update:cube="updateCube" />
        </section>

        <!-- Tools sidebar -->
        <section class="app__section app__section--sidebar">
          <ExportPanel
            :current-cube="currentCube"
            @cube-load="loadCube"
            @cube-change="updateCube"
          />

          <ActionHistory :actions="[]" />
        </section>
      </main>
    </ComponentInfo>

    <GodModeWindow />
    <DevModeIndicator />
  </div>

  <!-- Tablet Layout -->
  <div v-else-if="isTablet" class="app app--tablet">
    <header class="app__header">
      <h1>isocubic</h1>
      <p>Web editor for parametric cubes</p>
    </header>

    <main class="app__main app__main--tablet">
      <!-- Preview on top -->
      <div class="app__preview-section">
        <div class="app__3d-preview app__3d-preview--tablet">
          <CubePreview :config="currentCube" data-testid="cube-preview" />
        </div>
      </div>

      <!-- Panels below -->
      <div class="app__tablet-panels">
        <section class="app__section">
          <Gallery :current-cube="currentCube" @cube-select="selectCube" />
        </section>

        <section class="app__section app__section--sidebar">
          <UnifiedEditor :cube="currentCube" @update:cube="updateCube" />

          <PromptGenerator
            @cube-generated="selectCube"
            @cubes-generated="(cubes) => cubes.length > 0 && selectCube(cubes[0])"
          />

          <ExportPanel
            :current-cube="currentCube"
            @cube-load="loadCube"
            @cube-change="updateCube"
          />
        </section>
      </div>
    </main>

    <GodModeWindow />
    <DevModeIndicator />
  </div>

  <!-- Mobile Layout -->
  <div v-else class="app app--mobile" @touchstart="handleTouchStart" @touchend="handleTouchEnd">
    <header class="app__header app__header--mobile">
      <h1>isocubic</h1>
    </header>

    <!-- Tab Navigation -->
    <nav class="app__mobile-nav">
      <button
        v-for="tab in mobileTabs"
        :key="tab.id"
        class="app__mobile-tab"
        :class="{ 'app__mobile-tab--active': activeMobileTab === tab.id }"
        :aria-label="tab.label"
        @click="activeMobileTab = tab.id"
      >
        <span class="app__mobile-tab-icon">{{ tab.icon }}</span>
        <span class="app__mobile-tab-label">{{ tab.label }}</span>
      </button>
    </nav>

    <!-- Mobile Content -->
    <div class="app__mobile-content">
      <!-- Gallery Tab -->
      <div v-if="activeMobileTab === 'gallery'" class="app__mobile-panel">
        <Gallery :current-cube="currentCube" @cube-select="selectCube" />
      </div>

      <!-- Preview Tab -->
      <div
        v-if="activeMobileTab === 'preview'"
        class="app__mobile-panel app__mobile-panel--preview"
      >
        <div class="app__current-cube app__current-cube--mobile">
          <div class="app__3d-preview app__3d-preview--mobile">
            <CubePreview :config="currentCube" data-testid="cube-preview" />
          </div>
          <div class="app__cube-info">
            <p>
              <strong>{{
                currentCube?.meta?.name || currentCube?.id || 'No cube selected'
              }}</strong>
            </p>
            <p v-if="currentCube?.prompt">{{ currentCube.prompt }}</p>
          </div>
        </div>
      </div>

      <!-- Editor Tab -->
      <div v-if="activeMobileTab === 'editor'" class="app__mobile-panel">
        <UnifiedEditor :cube="currentCube" @update:cube="updateCube" />

        <PromptGenerator
          @cube-generated="selectCube"
          @cubes-generated="(cubes) => cubes.length > 0 && selectCube(cubes[0])"
        />
      </div>

      <!-- Tools Tab -->
      <div v-if="activeMobileTab === 'tools'" class="app__mobile-panel">
        <ExportPanel :current-cube="currentCube" @cube-load="loadCube" @cube-change="updateCube" />

        <ActionHistory :actions="[]" />
      </div>
    </div>

    <!-- Swipe Indicator -->
    <div class="app__swipe-indicator">
      <span>Swipe to navigate</span>
    </div>

    <DevModeIndicator />
  </div>
</template>
